Refactoring/crypto
KogarashiNetwork/Kogarashi pull request #73
Opened 2023-04-19 04:38 UTC by KiriosK

2023-04-25 06:03 UTC, ashWhiteHat requested changes

2023-04-25 06:03 UTC, ashWhiteHat commented on primitive/crypto/src/dress/curve/weierstrass/group.rs
> +        impl<'a> Mul<$scalar> for &'a $affine {
Can we move these to `refops`?

2023-04-25 06:03 UTC, ashWhiteHat commented on primitive/crypto/src/dress/curve/weierstrass/group.rs
> +                *self = (&*self - rhs).into();
I prefer `-=`.

2023-04-25 06:03 UTC, ashWhiteHat commented on primitive/crypto/src/dress/curve/weierstrass/group.rs
> +                *self - *rhs
Can we use `&` instead?

2023-04-25 06:03 UTC, ashWhiteHat commented on primitive/jubjub/src/curve.rs
> +}
It would be nice if we move these to `curve_test`.

2023-04-25 06:06 UTC, ashWhiteHat commented on primitive/bls12_381/src/g1.rs
> +    }
Next

2023-04-25 06:08 UTC, ashWhiteHat commented on primitive/crypto/src/dress/curve/weierstrass/group.rs
> +                *self - *rhs
not possible

2023-04-26 03:29 UTC, KiriosK commented on primitive/crypto/src/dress/curve/weierstrass/group.rs
> +        impl<'a> Mul<$scalar> for &'a $affine {
Done

2023-04-26 03:29 UTC, KiriosK commented on primitive/crypto/src/dress/curve/weierstrass/group.rs
> +                *self = (&*self - rhs).into();
Done

2023-04-26 03:29 UTC, KiriosK commented on primitive/crypto/src/behave/curve/basic.rs
> +    // + RefOps
Removed

2023-04-26 03:37 UTC, merged